services:
  - type: web
    name: tienda-virtual
    env: python
    plan: free  # 👈 esta línea es CLAVE
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
